### ISSUE TITLE
Linear time access to raw data

### ISSUE THREAD

**Issue by tilsche** [metricq/hta#1]
The current binary search access scheme in raw data seems to become a performance bottleneck due to high-latency requests. We have several options to get (near) linear access:

1. Assume somewhat equi-distant data and seek in the general vicinity of the requested time range. This may be a bit tricky, need some heuristic if we don't find the perfect spot. Also note that there is immediate practical optimization potential because currently begin/end index seeking is done indepedently. That allows us to know how much data we need to read at once, but requires to do a log(N) search two times.

2. Write index information in the lowest aggregate level (e.g. file position where each interval begins in raw data). This slightly increases the risk of inconsistency among aggregation levels. Also one could either extend the aggregation struct for each level (at the cost of redundancy on higher levels) or have different structs for only the lowest level (at the cost of file format complexity)

3. Write index information in a separate file similar to the lowest aggregate file. This has significant additional costs (file handle, additional write for each lowest-aggregation) but avoids having different structs for each layer.

Due to the impact on the file format, I would prefer to try 1) and see if we can get it working well practically.

**Comment by bmario** [comment]
This should be solved with b5140021c70afceed178405ad854fc7081042a04
